# Generated by Django 3.2.4 on 2022-07-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bed No.')),
                ('bed_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'Bed',
            },
        ),
        migrations.CreateModel(
            name='ComplainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='complain Type')),
            ],
            options={
                'verbose_name_plural': 'Complain Type',
            },
        ),
        migrations.CreateModel(
            name='ExpenseHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='expensce Head')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'Expense Head',
            },
        ),
        migrations.CreateModel(
            name='FeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='fee Group')),
            ],
            options={
                'verbose_name_plural': 'Fee Group',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='fee Type')),
                ('duedate', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Fee Type',
            },
        ),
        migrations.CreateModel(
            name='IncomeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='income Head')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'Income Head',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'Room Type',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Room No.')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('roomtype', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hostel.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('invoiceno', models.CharField(max_length=200, verbose_name='invoice No')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
                ('incomehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.incomehead')),
            ],
            options={
                'verbose_name_plural': 'Income',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('invoiceno', models.CharField(max_length=200, verbose_name='invoice No')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
                ('expensehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.expensehead')),
            ],
            options={
                'verbose_name_plural': 'Expense',
            },
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20, verbose_name='status')),
                ('complaintype', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hostel.complaintype')),
            ],
            options={
                'verbose_name_plural': 'Complain',
            },
        ),
        migrations.CreateModel(
            name='Boarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('father_name', models.CharField(max_length=200, verbose_name='father Name')),
                ('cell_no', models.CharField(max_length=200, verbose_name='cell No')),
                ('photo', models.ImageField(upload_to='students_pics/')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('emergency_cell_no', models.CharField(max_length=200, verbose_name='Emergency Cell No')),
                ('living_purpose', models.CharField(choices=[('Study', 'Study'), ('Job', 'Job')], default='Study', max_length=20, verbose_name='living Purpose')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=20, verbose_name='blood Group')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notes')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_beds', to='hostel.bed')),
                ('feegroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.feegroup')),
            ],
            options={
                'verbose_name_plural': 'Boarder',
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hostel.room'),
        ),
    ]
