# Generated by Django 3.2.4 on 2022-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_feetype_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feegroup',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
