# Generated by Django 3.2.4 on 2022-07-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_feegroup_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='bed_price',
        ),
    ]
