# Generated by Django 3.2.4 on 2022-07-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_collectfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectfee',
            name='amountpaid',
            field=models.PositiveIntegerField(verbose_name='amount Paid'),
        ),
    ]
