# Generated by Django 3.2.4 on 2022-07-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_alter_collectfee_amountpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectfee',
            name='amountdue',
            field=models.PositiveIntegerField(default=1, verbose_name='amount Due'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectfee',
            name='balance',
            field=models.PositiveIntegerField(default=1, verbose_name='Balance'),
            preserve_default=False,
        ),
    ]
