# Generated by Django 3.2.4 on 2022-07-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_auto_20220727_0232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectFee',
        ),
    ]
