# Generated by Django 3.2.4 on 2022-07-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_delete_collectfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountdue', models.PositiveIntegerField(verbose_name='amount Due')),
                ('amountpaid', models.PositiveIntegerField(verbose_name='amount Paid')),
                ('balance', models.PositiveIntegerField(verbose_name='Balance')),
                ('boarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.boarder')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype')),
            ],
            options={
                'verbose_name_plural': 'Collect Fee',
            },
        ),
    ]
