# Generated by Django 3.2.4 on 2022-07-26 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_collectfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.roomtype'),
        ),
    ]
