# Generated by Django 3.2.4 on 2022-09-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_alter_room_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavingdate', models.DateField()),
                ('boarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.boarder')),
            ],
            options={
                'verbose_name_plural': 'Leaving Notice',
            },
        ),
    ]
