# Generated by Django 3.2.4 on 2022-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_leavenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavenotice',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='description'),
        ),
    ]
