# Generated by Django 3.2.4 on 2022-09-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_leavenotice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Inprocess', 'Inprocess'), ('Completed', 'Completed')], default='Pending', max_length=20, verbose_name='status')),
                ('duedate', models.DateField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Todo List',
            },
        ),
    ]
