# Generated by Django 3.2.4 on 2022-09-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_auto_20220906_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='photo',
            field=models.ImageField(blank=True, upload_to='students_pics/'),
        ),
    ]
