# Generated by Django 3.2.4 on 2022-09-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_alter_boarder_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='photo',
            field=models.ImageField(default=1, upload_to='students_pics/'),
            preserve_default=False,
        ),
    ]
