# Generated by Django 3.2.4 on 2022-09-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_alter_boarder_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Fee Type'},
        ),
        migrations.AddField(
            model_name='boarder',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='admission Date'),
        ),
    ]
