# Generated by Django 3.2.4 on 2022-09-14 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0021_auto_20220913_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
