# Generated by Django 3.2.4 on 2022-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_collectfee_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectfee',
            name='datepaid',
            field=models.DateField(blank=True, null=True, verbose_name='Collection Date'),
        ),
    ]
