# Generated by Django 3.2.4 on 2022-09-14 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0023_collectfee_datepaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectfee',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='collectfee',
            name='datepaid',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
