# Generated by Django 4.1.5 on 2023-02-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0025_alter_collectfee_datepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
